### ISSUE TITLE
Enable network tests for LIGO on CI

### ISSUE THREAD

**Issue by gromakovsky** [tezos-commons/baseDAO#124]
# Clarification and motivation

We pass `--nettest-no-run-network` in `ligo-test` on CI. That's because our LIGO contract is too big and can't be originated easily. See also #123, we likely need to do it first.

# Acceptance criteria

CI runs tests for the LIGO contract with `--nettest-run-network` enabled.

**Comment by rvem** [comment]
I've checked ligo network tests in #148. The origination works now, but most of the tests fail with insufficient xtz error. Also, tests take ~30 to finish on a single local-chain. So, apparently, we should consider adding batching before adding such long-running tests to CI

**Comment by pasqu4le** [comment]
Additional note: running locally after #148 it seems that the additional funds assigned to `admin` in `Test.Ligo.BaseDAO.Common`'s `defaultStartupContract` should be increased to check for a minimum of `4 XTZ`.

**Comment by pasqu4le** [comment]
Addition, with #163 we use `morley-large-originator` to both Lorentz and Ligo versions, so this now extends to reactivating both's nettests.

Note that with those changes the Ligo origination/startup time has gone down a lot, as there's now the need for ~4 operations compared to the previous ~20.
However this still hold unacceptable times and will likely need upstream tooling improvements.
