### ISSUE TITLE
Reduce running time of nettests in local chain

### ISSUE THREAD

**Issue by pasqu4le** [tezos-commons/baseDAO#139]
# Clarification and motivation

Tests take quite a lot of time in local chain and we often have to wait for CI for quite long.

Currently waiting times are tolerable, but when we enable network tests for LIGO (see #124 ), they will increase and they will probably continue increasing as we add more features. So we'll soon need to reduce the required time.

Possible solutions: use batching  or replace usages of view entrypoints with direct storage checking (this connects this issue to #31 and consequently to morley/346.

# Acceptance criteria

The network tests time cost for CI is reduced (or kept) to being a tolerable waiting time for PRs.

**Comment by pasqu4le** [comment]
cc @Martoon-00 as I think you were planning on introducing batching.

**Comment by gromakovsky** [comment]
> use batching or replace usages of view entrypoints with direct storage checking

Eventually we should do both I think, but currently both are somewhat blocked.

**Comment by Martoon-00** [comment]
I'm planning to [rewrite batching interface in Morley](https://gitlab.com/morley-framework/morley/-/issues/403) within days, then once making a release we can start using batching freely here.
