### ISSUE TITLE
Review RegistryDAO for size optimizations

### ISSUE THREAD

**Issue by michaeljklein** [tezos-commons/baseDAO#174]
# Clarification and motivation

As in https://github.com/tqtezos/baseDAO/issues/38, RegistryDAO exceeds the operation size limit during origination.

# Acceptance criteria

Perform a general analysis of how the contract can be made smaller, including a "profile" of the contract as found here: https://docs.google.com/spreadsheets/d/16_8XLE-ERIVGqpzbIQDhxeHlPPza7bOpF6JcdTI7FWQ/edit#gid=0

**Comment by pasqu4le** [comment]
Closing this as it's now very outdated (registryDAO still exists, but it's a different thing and is also more efficient)
