### ISSUE TITLE
Support TZIP-21 in the generated contract metadata

### ISSUE THREAD

**Issue by pasqu4le** [tezos-commons/baseDAO#240]
# Clarification and motivation

We currently generate contract metadata that is compliant to [TZIP-16](https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-16/tzip-16.md) but not [TZIP-21](https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-21/tzip-21.md).

Since many wallets prefer/value support for TZIP-21 we should include it in baseDAO as well.

# Acceptance criteria

The generated contract metadata is TZIP-21 compliant.

**Comment by pasqu4le** [comment]
Note: since TZIP-21 is still a `Draft` we should target a specific version/commit for the time being.

**Comment by jacobarluck** [comment]
Updating to p1
