### ISSUE TITLE
Check the updated value of a field in `Storage` in tests to ensure the value is updated properly

### ISSUE THREAD

**Issue by rinn7e** [tezos-commons/baseDAO#31]
# Clarification and motivation

Currently, it is not possible to do a `checkStorage` on a `Storage` that contains `BigMap`. 
We are not able to check just a field value of a `Storage` that contains `BigMap` as well.

This prevents from check the updated value properly in the tests for proposal-related entrypoints.

Thread for more detail: https://serokell.slack.com/archives/CF2UVU8RX/p1603886730046500?thread_ts=1603706879.484000&cid=CF2UVU8RX

# Acceptance criteria
- When it is possible to check a value of a field `Storage`, use it to check the updated storage in the proposal-related tests to ensure it works properly.
- All TODOs related to #31 is removed.

**Comment by Martoon-00** [comment]
I want to wait to see how https://gitlab.com/morley-framework/morley/-/issues/346 will be resolved unless it takes long, the currently available solutions are not very pleasant.

**Comment by gromakovsky** [comment]
morley#346 is now in progress and it's pretty much required here. Let's wait for it. I am unassigning this issue for now, let's come back when morley#346 is available.

**Comment by sras** [comment]
We have also skipped tests in [this PR](https://github.com/tqtezos/baseDAO/pull/149) for lack of this capability, so we should also implement tests there as well, once this capability is available.

**Comment by sras** [comment]
Resolved by https://github.com/tezos-commons/baseDAO/pull/294
